# dev-a — qa-security namespace on dev_a cluster
# helm upgrade --install fp-airflow ./charts-airflow -f charts-airflow/awsuswest2deva-qasecurity/values.yaml -n qa-security

airflow:
  webserver:
    adminPassword: "admin"
    service:
      type: NodePort
      port: 8080
      nodePort: 31080

postgresql:
  storageClass: aws-ebs-csi
