apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-env
  labels:
    app.kubernetes.io/name: airflow
    {{- include "chart.labels" . | nindent 4 }}
data:
  AIRFLOW__CORE__EXECUTOR: {{ .Values.airflow.executor | quote }}
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://{{ .Values.postgresql.username }}:$(POSTGRES_PASSWORD)@airflow-db:5432/{{ .Values.postgresql.database }}"
  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  AIRFLOW__CORE__DAGS_FOLDER: "/opt/airflow/dags"
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
  AIRFLOW__KUBERNETES_EXECUTOR__NAMESPACE: {{ .Release.Namespace | quote }}
  AIRFLOW__KUBERNETES_EXECUTOR__WORKER_CONTAINER_REPOSITORY: {{ .Values.airflow.image | regexFind "^[^:]*" | quote }}
  AIRFLOW__KUBERNETES_EXECUTOR__WORKER_CONTAINER_TAG: {{ .Values.airflow.image | regexFind ":[^:]*$" | trimPrefix ":" | quote }}
  AIRFLOW__KUBERNETES_EXECUTOR__WORKER_SERVICE_ACCOUNT_NAME: "airflow"
  AIRFLOW__KUBERNETES_EXECUTOR__DELETE_WORKER_PODS: "true"
  AIRFLOW__KUBERNETES_EXECUTOR__DELETE_WORKER_PODS_ON_FAILURE: "false"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-auth
  labels:
    app.kubernetes.io/name: airflow
    {{- include "chart.labels" . | nindent 4 }}
data:
  passwords.json: |
    {{ printf "{\"%s\": \"%s\"}" .Values.airflow.webserver.adminUser .Values.airflow.webserver.adminPassword }}
