apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow
  labels:
    app.kubernetes.io/name: airflow
    {{- include "chart.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow
  labels:
    app.kubernetes.io/name: airflow
    {{- include "chart.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow
  labels:
    app.kubernetes.io/name: airflow
    {{- include "chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: airflow
subjects:
  - kind: ServiceAccount
    name: airflow
    namespace: {{ .Release.Namespace }}
