# awsuswest2deva — qa-security namespace on dev_a cluster
# helm upgrade --install fp-starrocks ./charts-starrocks -f charts-starrocks/awsuswest2deva-qasecurity/values.yaml -n qa-security

starrocks:
  fe:
    s3:
      bucket: datavisor-dev-us-west-2-iceberg
      path: "cre-6630/qa-security/starrocks-data/"
