apiVersion: v1
kind: ConfigMap
metadata:
  name: starrocks-cn-config
  labels:
    app.kubernetes.io/name: starrocks-cn
    {{- include "chart.labels" . | nindent 4 }}
data:
  cn.conf: |
    LOG_DIR = ${STARROCKS_HOME}/log
    JAVA_OPTS="-Dlog4j2.formatMsgNoLookups=true -Xmx4096m -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError"

    thrift_port = 9060
    webserver_port = 8040
    heartbeat_service_port = 9050
    brpc_port = 8060
    starlet_port = 9070
---
apiVersion: v1
kind: Service
metadata:
  name: starrocks-cn
  labels:
    app.kubernetes.io/name: starrocks-cn
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: heartbeat
      port: 9050
      targetPort: 9050
    - name: http
      port: 8040
      targetPort: 8040
    - name: thrift
      port: 9060
      targetPort: 9060
    - name: brpc
      port: 8060
      targetPort: 8060
  selector:
    app.kubernetes.io/name: starrocks-cn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: starrocks-cn
  labels:
    app.kubernetes.io/name: starrocks-cn
    {{- include "chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.starrocks.cn.hpa.enabled }}
  replicas: {{ .Values.starrocks.cn.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: starrocks-cn
  template:
    metadata:
      labels:
        app.kubernetes.io/name: starrocks-cn
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8040"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: starrocks-cn
          image: {{ .Values.starrocks.cn.image }}
          command: ["/opt/starrocks/cn/bin/start_cn.sh"]
          ports:
            - containerPort: 9050
              name: heartbeat
            - containerPort: 8040
              name: http
            - containerPort: 9060
              name: thrift
            - containerPort: 8060
              name: brpc
            - containerPort: 9070
              name: starlet
          readinessProbe:
            tcpSocket:
              port: 9050
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9050
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            {{- toYaml .Values.starrocks.cn.resources | nindent 12 }}
          volumeMounts:
            - name: cn-config
              mountPath: /opt/starrocks/cn/conf/cn.conf
              subPath: cn.conf
            - name: cn-cache
              mountPath: /opt/starrocks/cn/storage
      volumes:
        - name: cn-config
          configMap:
            name: starrocks-cn-config
        - name: cn-cache
          emptyDir:
            sizeLimit: {{ .Values.starrocks.cn.cacheSizeLimit }}
{{- if .Values.starrocks.cn.hpa.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: starrocks-cn
  labels:
    app.kubernetes.io/name: starrocks-cn
    {{- include "chart.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: starrocks-cn
  minReplicas: {{ .Values.starrocks.cn.hpa.minReplicas }}
  maxReplicas: {{ .Values.starrocks.cn.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.starrocks.cn.hpa.targetCPUUtilizationPercentage }}
{{- end }}
