apiVersion: v1
kind: ConfigMap
metadata:
  name: starrocks-fe-config
  labels:
    app.kubernetes.io/name: starrocks-fe
    {{- include "chart.labels" . | nindent 4 }}
data:
  fe.conf: |
    LOG_DIR = ${STARROCKS_HOME}/log
    DATE = "$(date +%Y%m%d-%H%M%S)"
    JAVA_OPTS="-Dlog4j2.formatMsgNoLookups=true -Xmx4096m -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError"

    http_port = 8030
    rpc_port = 9020
    query_port = 9030
    edit_log_port = 9010

    run_mode = shared_data
    cloud_native_meta_port = 6090

    cloud_native_storage_type = S3
    aws_s3_use_instance_profile = {{ .Values.starrocks.fe.s3.useInstanceProfile }}
    aws_s3_region = {{ .Values.starrocks.fe.s3.region }}
    aws_s3_endpoint = s3.{{ .Values.starrocks.fe.s3.region }}.amazonaws.com
    aws_s3_bucket = {{ .Values.starrocks.fe.s3.bucket }}
    aws_s3_path = {{ .Values.starrocks.fe.s3.path }}
---
apiVersion: v1
kind: Service
metadata:
  name: starrocks-fe
  labels:
    app.kubernetes.io/name: starrocks-fe
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: mysql
      port: 9030
      targetPort: 9030
    - name: http
      port: 8030
      targetPort: 8030
    - name: rpc
      port: 9020
      targetPort: 9020
    - name: edit-log
      port: 9010
      targetPort: 9010
  selector:
    app.kubernetes.io/name: starrocks-fe
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: starrocks-fe
  labels:
    app.kubernetes.io/name: starrocks-fe
    {{- include "chart.labels" . | nindent 4 }}
spec:
  serviceName: starrocks-fe
  replicas: {{ .Values.starrocks.fe.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: starrocks-fe
  template:
    metadata:
      labels:
        app.kubernetes.io/name: starrocks-fe
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8030"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: starrocks-fe
          image: {{ .Values.starrocks.fe.image }}
          command: ["/opt/starrocks/fe/bin/start_fe.sh", "--host_type", "FQDN"]
          ports:
            - containerPort: 8030
              name: http
            - containerPort: 9030
              name: mysql
            - containerPort: 9020
              name: rpc
            - containerPort: 9010
              name: edit-log
            - containerPort: 6090
              name: cloud-meta
          readinessProbe:
            tcpSocket:
              port: 9030
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 9030
            initialDelaySeconds: 120
            periodSeconds: 20
            failureThreshold: 5
          resources:
            {{- toYaml .Values.starrocks.fe.resources | nindent 12 }}
          volumeMounts:
            - name: fe-config
              mountPath: /opt/starrocks/fe/conf/fe.conf
              subPath: fe.conf
            - name: fe-meta
              mountPath: /opt/starrocks/fe/meta
      volumes:
        - name: fe-config
          configMap:
            name: starrocks-fe-config
  volumeClaimTemplates:
    - metadata:
        name: fe-meta
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.starrocks.fe.storageClass }}
        resources:
          requests:
            storage: {{ .Values.starrocks.fe.storageSize }}
