fpMysql:
  host: fp-mysql.preprod

iceberg:
  restCatalog:
    s3:
      bucket: datavisor-preprod-us-east-1-iceberg
      region: us-east-1
      warehousePrefix: "s3://datavisor-preprod-us-east-1-iceberg/cre-6630/preprod/"

kafkaConnect:
  bootstrapServers: "kafka3.preprod:9092"
  replicationFactor: 3
  smtJarS3Uri: "s3://datavisor-preprod-us-east-1-iceberg/cre-6630/smt/fp-feature-smt-1.0.0.jar"
