apiVersion: v1
kind: Secret
metadata:
  name: iceberg-rest-catalog-secret
  namespace: qa-security
  labels:
    app: iceberg-rest-catalog
type: Opaque
stringData:
  jdbc-user: "iceberg"
  jdbc-password: "CHANGE_ME"
