# awsuswest2preproda — preprod namespace on preprod_a cluster
# helm upgrade --install fp-iceberg ./charts-iceberg -f charts-iceberg/awsuswest2preproda/values.yaml -n preprod

fpMysql:
  host: fp-mysql.preprod

iceberg:
  restCatalog:
    s3:
      bucket: datavisor-preprod-us-west-2-iceberg
      warehousePrefix: "s3://datavisor-preprod-us-west-2-iceberg/cre-6630/preprod/"

kafkaConnect:
  bootstrapServers: "kafka3.preprod:9092"
  replicationFactor: 1
  smtJarS3Uri: "s3://datavisor-preprod-us-west-2-iceberg/cre-6630/smt/fp-feature-smt-1.0.0.jar"
