# awsuswest2deva — qa-security namespace on dev_a cluster
# helm upgrade --install fp-iceberg ./charts-iceberg -f charts-iceberg/awsuswest2deva-qasecurity/values.yaml -n qa-security
#
# NOTE: qa-security namespace has only 1 Kafka broker, so replicationFactor=1

fpMysql:
  host: fp-mysql.qa-security

iceberg:
  restCatalog:
    s3:
      bucket: datavisor-dev-us-west-2-iceberg
      warehousePrefix: "s3://datavisor-dev-us-west-2-iceberg/cre-6630/qa-security/"

kafkaConnect:
  bootstrapServers: "kafka3.qa-security:9092"
  replicationFactor: 1
  smtJarS3Uri: "s3://datavisor-dev-us-west-2-iceberg/cre-6630/smt/fp-feature-smt-1.0.0.jar"
